version: '3.7'

services:
  bitwarden:
    build: .
    restart: always
    ports:
      - '80:80'
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: bitwarden
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
